export const dummy = [
    {
        id:"0",
        src: "https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1564542857176l0.jpg",
        alt: "세트",
        title: "[선물세트] 옥돔&갈치&민어굴비 세트",
        discount: "35%",
        sale_price: "116,350원",
    },
    {
        id:"1",
        src: "https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1640326599530l0.jpg",
        alt: "에스티로더",
        title: "[에스티 로더] 갈색병 세럼 50ml 기획 세트 (+45ml 추가 증정)",
        discount: "15%",
        sale_price: "148,750원",
    },
    {
        id:"2",
        src: "https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1640326599530l0.jpg",
        alt: "선물세트",
        title: "[선물세트] 한삼인 기운담은 선물세트",
        discount: "55%",
        sale_price: "26,820원~",
    },
    {
        id:"3",
        src: "./assets/items/recommend1.avif",
        alt: "미미네 떡볶이",
        title: "미미네 떡볶이",
        discount: "",
        sale_price: "",
    },
    {
        id:"4",
        src: "./assets/items/recommend2.avif",
        alt: "[풀무원] 생면식감 꽃게탕면",
        title: "[풀무원] 생면식감 꽃게탕면",
        discount: "25%",
        sale_price: "4,088원",
    },
    {
        id:"5",
        src: "./assets/items/recommend3.avif",
        alt: "[삼삼물산] 남해안 자연산 손질 바위굴 1kg (냉장)",
        title: "[삼삼물산] 남해안 자연산 손질 바위굴 1kg (냉장)",
        discount: "10%",
        sale_price: "22,400원",
    },
    {
        id:"6",
        src: "./assets/items/recommend4.avif",
        alt: "[탐육] 토마토 미트볼",
        title: "[탐육] 토마토 미트볼",
        discount: "",
        sale_price: "11,000원",
    },
    {
        id:"7",
        src: "./assets/items/recommend5.avif",
        alt: "[브로드카세] 부드러운 비엔나 쿠키 4종",
        title: "[브로드카세] 부드러운 비엔나 쿠키 4종",
        discount: "",
        sale_price: "5,500원",
    },
    {
        id:"8",
        src: "./assets/items/recommend6.avif",
        alt: "[글라스락] 곰표 계량컵",
        title: "[글라스락] 곰표 계량컵",
        discount: "",
        sale_price: "15,900원",
    },
    {
        id:"9",
        src: "./assets/items/recommend7.avif",
        alt: "[그녀의빵공장] 라우겐",
        title: "[그녀의빵공장] 라우겐",
        discount: "",
        sale_price: "2,500원",
    },
    {
        id:"10",
        src: "./assets/items/recommend8.avif",
        alt: "[리큅] 스마트UV 변기살균기 LST-UV3L",
        title: "[리큅] 스마트UV 변기살균기 LST-UV3L",
        discount: "31%",
        sale_price: "29,610원",
    },
];